### ISSUE TITLE
live-reloading broken in some cases

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt-frontend-demo#4]
In the Tilt slack channel, someone reported that this doesn't appear to live-reload anymore in certain cluster configurations.

Tilt appears to be copying the file into the container correctly, but React doesn't live reload it

**Comment by jazzdan** [comment]
@nicks can you link to the conversation please?

**Comment by nicks** [comment]
https://kubernetes.slack.com/archives/CESBL84MV/p1582498431007300

**Comment by nicks** [comment]
confirmed that this is definitely a bug in webpack's file watching. If I exec into the container and use entr to watch the files:

```
echo src/App.js | entr echo "update"
```

The OS is getting the file updates
